FROM nginx
# overwrite the default.conf file in nginx folder in the original image
COPY ./default.conf /etc/nginx/conf.d/default.conf

# don't overwrite default command in nginx image, so the original one takes precendence